Rework backup script a little bit

diff --git a/nubis/puppet/files/ldap/ldap-backup b/nubis/puppet/files/ldap/ldap-backup
--- a/nubis/puppet/files/ldap/ldap-backup
+++ b/nubis/puppet/files/ldap/ldap-backup
@@ -14,19 +14,23 @@ umask 027
 # Please don't tell me to use mktemp,
 # if you want to use mktemp patches are welcomed
 date_format=$(date +\%Y-\%m-\%d_\%H:\%M:\%S)
-backup_file="backup-${date_format}.ldif"
+backup_file="backup-${date_format}.ldif.gz"
 s3_bucket="${NUBIS_STACK}-${REGION}-backupbucket"
 
 # Slapcat the database
-/usr/sbin/slapcat | gzip -c > /tmp/${backup_file}.gz
+log "Backing up LDAP database"
+/usr/sbin/slapcat | gzip -c > /tmp/${backup_file}
 
-aws s3 cp --sse /tmp/${backup_file}.gz s3://${s3_bucket}
-RV=$?
+if [[ -s /tmp/${backup_file} ]]; then
+    for DEST in ${backup_file} latest.ldif.gz; do
+        log "Attempting to backup ${DEST} to S3 (${s3_bucket})"
+        aws s3 cp --sse /tmp/${backup_file} s3://${s3_bucket}/${DEST} --quiet
+        RV=$?
 
-if [[ ${RV} != 0 ]]; then
-    log "ERROR: Unable to upload file (${backup_file}.gz) to S3 bucket (${s3_bucket})"
-else
-    log "SUCCESS: Uploaded backup file (${backup_file}.gz) to S3 bucket (${s3_bucket})"
+        if [[ ${RV} -ne 0 ]]; then
+            log "ERROR: RV value is ${RV} and unable to backup ${DEST} to S3"
+        fi
+    done
 fi
 
 # cleanup
